[package]
name = "coil_calculator"
version = "0.1.0"
edition = "2024"
authors = ["Felix Buchsteiner <contact@gl1tchxd.at", "Matthias Kühner <matthias.kuehner08@htl-salzburg.ac.at"]
homepage = "https://github.com/gl1tchxd-git/Feldstaerke-Calc/tree/rust-lib"
repository = "https://github.com/gl1tchxd-git/Feldstaerke-Calc/tree/rust-lib"
description = "Library for calculating field force inside various coils"

[dependencies]