name: Sync Rust Library

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-rust-lib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Fetch rust-lib branch
      run: git fetch origin rust-lib

    - name: Check if branches are different
      id: check_diff
      run: |
        git diff --quiet origin/rust-lib || echo "branches are different" > diff.txt

    - name: Copy src/library to rust-lib branch
      if: steps.check_diff.outputs.diff
      run: |
        git checkout rust-lib
        cp -r src/library/* .
        git add .
        git commit -m "Sync library from master"
        git push origin rust-lib
