name: Sync Library

on:
  push:
    branches:
      - master

jobs:
  sync-library:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check for updates in src/library
      id: check_changes
      run: |
        changes=$(git diff --name-only HEAD^ HEAD src/library/)
        echo "changes=$changes" >> $GITHUB_ENV

    - name: Sync library to rust-lib branch
      if: env.changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        git checkout rust-lib

        # Ensure src/library directory exists
        if [ -d "src/library" ]; then
          rsync -a --delete src/library/ .
        else
          echo "src/library directory does not exist. Skipping rsync."
          exit 0
        fi
        
        git add .
        git commit -m "Sync library from master branch"
        git push origin rust-lib
