name: Sync Library Folder

on:
  push:
    branches:
      - master
    paths:
      - 'src/library/**'

jobs:
  sync-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check for changes in src/library
        id: check_changes
        run: |
          git fetch origin rust-lib
          git diff --quiet HEAD origin/rust-lib -- src/library || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Checkout rust-lib branch
        if: env.changes_detected == 'true'
        run: git checkout rust-lib

      - name: Sync library folder to rust-lib branch
        if: env.changes_detected == 'true'
        run: |
          rsync -a --delete src/library/ .
          git add .
          git commit -m "Sync src/library from master branch" || echo "No changes to commit"
          git push origin rust-lib

      - name: Debugging - List files in rust-lib branch
        if: env.changes_detected == 'true'
        run: |
          git checkout rust-lib
          ls -la
