name: Sync Rust Library

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-rust-lib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout rust-lib branch
      run: git checkout rust-lib

    - name: Compare branches
      id: check_diff
      run: |
        if git diff --quiet origin/master; then
          echo "branches_are_same=true" >> $GITHUB_ENV
        else
          echo "branches_are_same=false" >> $GITHUB_ENV
        fi

    - name: Display diff result
      run: echo "Branches are different, proceeding with copy"

    - name: Set up Git user
      if: env.branches_are_same == 'false'
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Copy src/library to rust-lib branch
      if: env.branches_are_same == 'false'
      run: |
        git checkout master
        mkdir -p ../rust-lib
        cp -r src/library/* ../rust-lib/
        git checkout rust-lib
        cp -r ../rust-lib/* .
        git add .
        git commit -m "Sync library from master"
        git push origin rust-lib
