name: Sync Rust Library

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync-rust-lib:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout rust-lib branch
      run: git checkout rust-lib

    - name: Compare branches
      id: check_diff
      run: |
        git diff --quiet origin/master || echo "branches are different" > diff.txt

    - name: Display diff result
      if: success()
      run: cat diff.txt

    - name: Copy src/library to rust-lib branch
      if: success() && steps.check_diff.outputs.diff
      run: |
        git checkout master
        cp -r src/library/* ../rust-lib/
        git checkout rust-lib
        cp -r ../rust-lib/* .
        git add .
        git commit -m "Sync library from master"
        git push origin rust-lib
